# Generated by Django 5.1 on 2026-02-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelmetDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('battery_level', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('GAS', 'Hazardous Gas'), ('FALL', 'Fall Detected'), ('FATIGUE', 'Fatigue Detected'), ('HEART', 'Abnormal Heart Rate')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.helmetdevice')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('gas_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('motion', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.helmetdevice')),
            ],
        ),
        migrations.AddField(
            model_name='helmetdevice',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.worker'),
        ),
    ]
