# Generated by Django 6.0.3 on 2026-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_worker_user_alter_helmetdevice_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='motion',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='fall_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='motion_x',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='motion_y',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
