# Generated by Django 6.0.3 on 2026-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_remove_sensordata_motion_sensordata_fall_detected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='motion',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
